#include "api5_effect_batch.hpp"
namespace api5 {
EffectStateBatchBuilder::EffectStateBatchBuilder(){batch_.StructSize=sizeof(batch_);batch_.ApiVersion=5;}
#define COPY(name,field) EffectStateBatchBuilder& EffectStateBatchBuilder::name(std::span<const decltype(field)::value_type> v){field.assign(v.begin(),v.end());return *this;}
EffectStateBatchBuilder& EffectStateBatchBuilder::transforms(std::span<const D3D9GtaSaTransformBinding>v){transforms_.assign(v.begin(),v.end());return *this;} EffectStateBatchBuilder& EffectStateBatchBuilder::renderStates(std::span<const D3D9GtaSaRenderStateBinding>v){states_.assign(v.begin(),v.end());return *this;}
EffectStateBatchBuilder& EffectStateBatchBuilder::vertexFloat(std::span<const D3D9GtaSaFloatConstantRange>v){vf_.assign(v.begin(),v.end());return *this;} EffectStateBatchBuilder& EffectStateBatchBuilder::pixelFloat(std::span<const D3D9GtaSaFloatConstantRange>v){pf_.assign(v.begin(),v.end());return *this;} EffectStateBatchBuilder& EffectStateBatchBuilder::vertexInt(std::span<const D3D9GtaSaIntConstantRange>v){vi_.assign(v.begin(),v.end());return *this;} EffectStateBatchBuilder& EffectStateBatchBuilder::pixelInt(std::span<const D3D9GtaSaIntConstantRange>v){pi_.assign(v.begin(),v.end());return *this;} EffectStateBatchBuilder& EffectStateBatchBuilder::vertexBool(std::span<const D3D9GtaSaBoolConstantRange>v){vb_.assign(v.begin(),v.end());return *this;} EffectStateBatchBuilder& EffectStateBatchBuilder::pixelBool(std::span<const D3D9GtaSaBoolConstantRange>v){pb_.assign(v.begin(),v.end());return *this;}
EffectStateBatchBuilder& EffectStateBatchBuilder::flags(UINT f){batch_.Flags=f;return *this;} EffectStateBatchBuilder& EffectStateBatchBuilder::fvf(DWORD f){batch_.FVF=f;batch_.Flags|=D3D9_GTA_SA_EFFECT_STATE_HAS_FVF;return *this;} EffectStateBatchBuilder& EffectStateBatchBuilder::material(const D3DMATERIAL9&m){batch_.Material=m;batch_.Flags|=D3D9_GTA_SA_EFFECT_STATE_HAS_MATERIAL;return *this;}
std::expected<const D3D9GtaSaEffectStateBatch*,std::string> EffectStateBatchBuilder::validate() noexcept { batch_.TransformCount=(UINT)transforms_.size();batch_.Transforms=transforms_.data();batch_.RenderStateCount=(UINT)states_.size();batch_.RenderStates=states_.data();batch_.VertexFloatRangeCount=(UINT)vf_.size();batch_.VertexFloatRanges=vf_.data();batch_.PixelFloatRangeCount=(UINT)pf_.size();batch_.PixelFloatRanges=pf_.data();batch_.VertexIntRangeCount=(UINT)vi_.size();batch_.VertexIntRanges=vi_.data();batch_.PixelIntRangeCount=(UINT)pi_.size();batch_.PixelIntRanges=pi_.data();batch_.VertexBoolRangeCount=(UINT)vb_.size();batch_.VertexBoolRanges=vb_.data();batch_.PixelBoolRangeCount=(UINT)pb_.size();batch_.PixelBoolRanges=pb_.data(); if(batch_.Flags&~(31u))return std::unexpected("unknown effect flags"); if(batch_.StructSize<sizeof(batch_)||batch_.ApiVersion!=5)return std::unexpected("ABI version/size"); for(auto&s:states_)if(UINT(s.State)>255u||(UINT(s.State)!=0&&UINT(s.State)<UINT(D3DRS_ZENABLE)))return std::unexpected("invalid render state"); return &batch_; }
}
